/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-11-20 12:02:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.forum;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class forum_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1763621232000L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1763638666000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String ctx = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- BOOTSTRAP CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- BOOTSTRAP ICONS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- CUSTOM CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( ctx );
      out.write("/assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- BOOTSTRAP JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<header class=\"site-header container mt-4 mb-3 d-flex align-items-center gap-3\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Logo -->\r\n");
      out.write("    <img src=\"");
      out.print( ctx );
      out.write("/assets/image/logo.jpg\"\r\n");
      out.write("         alt=\"Logo\"\r\n");
      out.write("         style=\"width:60px; height:60px; border-radius:6px; object-fit:cover;\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Title + Navigation -->\r\n");
      out.write("    <div>\r\n");
      out.write("        <h2 class=\"fw-bold mb-1\">CyberLearn</h2>\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"top-nav d-flex gap-4\">\r\n");
      out.write("\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/index.jsp\">Home</a>\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/courses\">Courses</a>\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/labs\">Labs</a>\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/forum\">Forum</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Discussion Forum - CyberLearn</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            background: linear-gradient(135deg, #0f0c29, #302b63, #24243e);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            color: #e0e0e0;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* <CHANGE> Animated background glow effect */\r\n");
      out.write("        body::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: -50%;\r\n");
      out.write("            left: -50%;\r\n");
      out.write("            width: 200%;\r\n");
      out.write("            height: 200%;\r\n");
      out.write("            background: radial-gradient(circle, rgba(100, 200, 255, 0.1) 0%, rgba(100, 200, 255, 0) 70%);\r\n");
      out.write("            animation: glowFloat 15s ease-in-out infinite;\r\n");
      out.write("            pointer-events: none;\r\n");
      out.write("            z-index: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: -50%;\r\n");
      out.write("            right: -50%;\r\n");
      out.write("            width: 200%;\r\n");
      out.write("            height: 200%;\r\n");
      out.write("            background: radial-gradient(circle, rgba(255, 100, 200, 0.1) 0%, rgba(255, 100, 200, 0) 70%);\r\n");
      out.write("            animation: glowFloat 20s ease-in-out infinite reverse;\r\n");
      out.write("            pointer-events: none;\r\n");
      out.write("            z-index: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes glowFloat {\r\n");
      out.write("            0%, 100% { transform: translate(0, 0); }\r\n");
      out.write("            50% { transform: translate(50px, 50px); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 40px 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            background: linear-gradient(135deg, #64c8ff, #ff64c8);\r\n");
      out.write("            -webkit-background-clip: text;\r\n");
      out.write("            -webkit-text-fill-color: transparent;\r\n");
      out.write("            background-clip: text;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .subtitle {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #b0b0b0;\r\n");
      out.write("            margin-bottom: 50px;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .forum-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));\r\n");
      out.write("            gap: 25px;\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .forum-card {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.05);\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            padding: 25px;\r\n");
      out.write("            transition: all 0.4s cubic-bezier(0.23, 1, 0.320, 1);\r\n");
      out.write("            cursor: default;\r\n");
      out.write("            animation: slideIn 0.6s ease-out forwards;\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .forum-card:nth-child(1) { animation-delay: 0.1s; }\r\n");
      out.write("        .forum-card:nth-child(2) { animation-delay: 0.2s; }\r\n");
      out.write("        .forum-card:nth-child(3) { animation-delay: 0.3s; }\r\n");
      out.write("        .forum-card:nth-child(4) { animation-delay: 0.4s; }\r\n");
      out.write("        .forum-card:nth-child(5) { animation-delay: 0.5s; }\r\n");
      out.write("        .forum-card:nth-child(6) { animation-delay: 0.6s; }\r\n");
      out.write("\r\n");
      out.write("        @keyframes slideIn {\r\n");
      out.write("            from {\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("                transform: translateY(30px);\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .forum-card:hover {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.08);\r\n");
      out.write("            border-color: rgba(255, 255, 255, 0.2);\r\n");
      out.write("            transform: translateY(-8px);\r\n");
      out.write("            box-shadow: 0 20px 60px rgba(100, 200, 255, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .post-header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 12px;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-avatar {\r\n");
      out.write("            width: 50px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            background: linear-gradient(135deg, #64c8ff, #0ea5e9);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            color: white;\r\n");
      out.write("            flex-shrink: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-avatar.blue { background: linear-gradient(135deg, #64c8ff, #0ea5e9); }\r\n");
      out.write("        .user-avatar.purple { background: linear-gradient(135deg, #a855f7, #7c3aed); }\r\n");
      out.write("        .user-avatar.pink { background: linear-gradient(135deg, #ec4899, #db2777); }\r\n");
      out.write("        .user-avatar.green { background: linear-gradient(135deg, #10b981, #059669); }\r\n");
      out.write("        .user-avatar.orange { background: linear-gradient(135deg, #f97316, #ea580c); }\r\n");
      out.write("        .user-avatar.cyan { background: linear-gradient(135deg, #06b6d4, #0891b2); }\r\n");
      out.write("\r\n");
      out.write("        .user-info h5 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            color: #e0e0e0;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .post-time {\r\n");
      out.write("            font-size: 0.85rem;\r\n");
      out.write("            color: #888;\r\n");
      out.write("            margin-top: 3px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .post-title {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .post-content {\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            color: #c0c0c0;\r\n");
      out.write("            margin-bottom: 12px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .post-meta {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("            font-size: 0.85rem;\r\n");
      out.write("            color: #888;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .post-meta span {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-btn {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("            padding: 12px 24px;\r\n");
      out.write("            background: linear-gradient(135deg, #64c8ff, #0ea5e9);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-btn:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 10px 30px rgba(100, 200, 255, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            h2 {\r\n");
      out.write("                font-size: 1.8rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .forum-grid {\r\n");
      out.write("                grid-template-columns: 1fr;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .container {\r\n");
      out.write("                padding: 20px 15px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2>Discussion Forum</h2>\r\n");
      out.write("        <p class=\"subtitle\">Community Learning & Knowledge Sharing</p>\r\n");
      out.write("\r\n");
      out.write("        <!-- <CHANGE> Hard-coded forum posts with futuristic card design -->\r\n");
      out.write("        <div class=\"forum-grid\">\r\n");
      out.write("            <!-- Post 1 -->\r\n");
      out.write("            <div class=\"forum-card\">\r\n");
      out.write("                <div class=\"post-header\">\r\n");
      out.write("                    <div class=\"user-avatar blue\">\r\n");
      out.write("                        <i class=\"fas fa-user\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"user-info\">\r\n");
      out.write("                        <h5>Alex Johnson</h5>\r\n");
      out.write("                        <p class=\"post-time\">2 hours ago</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"post-title\">Understanding Network Security Fundamentals</div>\r\n");
      out.write("                <p class=\"post-content\">I'm trying to understand the basics of network security. Could someone explain the differences between firewalls, VPNs, and proxies? Any resources would be helpful!</p>\r\n");
      out.write("                <div class=\"post-meta\">\r\n");
      out.write("                    <span><i class=\"fas fa-comment\"></i> 12 replies</span>\r\n");
      out.write("                    <span><i class=\"fas fa-heart\"></i> 24 likes</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Post 2 -->\r\n");
      out.write("            <div class=\"forum-card\">\r\n");
      out.write("                <div class=\"post-header\">\r\n");
      out.write("                    <div class=\"user-avatar purple\">\r\n");
      out.write("                        <i class=\"fas fa-shield-alt\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"user-info\">\r\n");
      out.write("                        <h5>Sarah Chen</h5>\r\n");
      out.write("                        <p class=\"post-time\">4 hours ago</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"post-title\">Best Practices for Password Security</div>\r\n");
      out.write("                <p class=\"post-content\">What are the latest best practices for creating and managing strong passwords? I've heard about passkeys - are they replacing traditional passwords?</p>\r\n");
      out.write("                <div class=\"post-meta\">\r\n");
      out.write("                    <span><i class=\"fas fa-comment\"></i> 18 replies</span>\r\n");
      out.write("                    <span><i class=\"fas fa-heart\"></i> 31 likes</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Post 3 -->\r\n");
      out.write("            <div class=\"forum-card\">\r\n");
      out.write("                <div class=\"post-header\">\r\n");
      out.write("                    <div class=\"user-avatar pink\">\r\n");
      out.write("                        <i class=\"fas fa-lock\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"user-info\">\r\n");
      out.write("                        <h5>Mike Rodriguez</h5>\r\n");
      out.write("                        <p class=\"post-time\">6 hours ago</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"post-title\">Exploring Ethical Hacking Career Path</div>\r\n");
      out.write("                <p class=\"post-content\">I'm interested in becoming a certified ethical hacker. Which certifications should I pursue first? CEH or OSCP? Looking for guidance from experienced professionals.</p>\r\n");
      out.write("                <div class=\"post-meta\">\r\n");
      out.write("                    <span><i class=\"fas fa-comment\"></i> 25 replies</span>\r\n");
      out.write("                    <span><i class=\"fas fa-heart\"></i> 45 likes</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Post 4 -->\r\n");
      out.write("            <div class=\"forum-card\">\r\n");
      out.write("                <div class=\"post-header\">\r\n");
      out.write("                    <div class=\"user-avatar green\">\r\n");
      out.write("                        <i class=\"fas fa-code\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"user-info\">\r\n");
      out.write("                        <h5>Emily Watson</h5>\r\n");
      out.write("                        <p class=\"post-time\">8 hours ago</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"post-title\">Python for Penetration Testing - Tips & Tricks</div>\r\n");
      out.write("                <p class=\"post-content\">Sharing some useful Python libraries for pentest automation. Let me know which tools you use most frequently in your security assessments!</p>\r\n");
      out.write("                <div class=\"post-meta\">\r\n");
      out.write("                    <span><i class=\"fas fa-comment\"></i> 9 replies</span>\r\n");
      out.write("                    <span><i class=\"fas fa-heart\"></i> 38 likes</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Post 5 -->\r\n");
      out.write("            <div class=\"forum-card\">\r\n");
      out.write("                <div class=\"post-header\">\r\n");
      out.write("                    <div class=\"user-avatar orange\">\r\n");
      out.write("                        <i class=\"fas fa-virus\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"user-info\">\r\n");
      out.write("                        <h5>James Park</h5>\r\n");
      out.write("                        <p class=\"post-time\">10 hours ago</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"post-title\">Malware Analysis - Where to Start?</div>\r\n");
      out.write("                <p class=\"post-content\">New to malware analysis here. What are the essential tools and sandboxes I should set up? Looking for step-by-step guidance to get started safely.</p>\r\n");
      out.write("                <div class=\"post-meta\">\r\n");
      out.write("                    <span><i class=\"fas fa-comment\"></i> 16 replies</span>\r\n");
      out.write("                    <span><i class=\"fas fa-heart\"></i> 28 likes</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Post 6 -->\r\n");
      out.write("            <div class=\"forum-card\">\r\n");
      out.write("                <div class=\"post-header\">\r\n");
      out.write("                    <div class=\"user-avatar cyan\">\r\n");
      out.write("                        <i class=\"fas fa-network-wired\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"user-info\">\r\n");
      out.write("                        <h5>Lisa Thompson</h5>\r\n");
      out.write("                        <p class=\"post-time\">12 hours ago</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"post-title\">Cloud Security Challenges & Solutions</div>\r\n");
      out.write("                <p class=\"post-content\">What are the main security concerns when migrating to the cloud? Any recommendations for securing AWS, Azure, or GCP environments?</p>\r\n");
      out.write("                <div class=\"post-meta\">\r\n");
      out.write("                    <span><i class=\"fas fa-comment\"></i> 22 replies</span>\r\n");
      out.write("                    <span><i class=\"fas fa-heart\"></i> 51 likes</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/dashboard.jsp\" class=\"back-btn\">\r\n");
      out.write("            <i class=\"fas fa-arrow-left\"></i> Back to Dashboard\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer class=\"site-footer container\">\r\n");
      out.write("  &copy; ");
      out.print( java.time.Year.now() );
      out.write(" CyberLearn. All rights reserved.\r\n");
      out.write("</footer>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
