/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-11-20 11:44:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.cyberlearn.model.User;

public final class manage_005fcourses_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1763621232000L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1763638666000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.cyberlearn.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\r');
      out.write('\n');

    String ctx = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- BOOTSTRAP CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- BOOTSTRAP ICONS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- CUSTOM CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( ctx );
      out.write("/assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- BOOTSTRAP JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<header class=\"site-header container mt-4 mb-3 d-flex align-items-center gap-3\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Logo -->\r\n");
      out.write("    <img src=\"");
      out.print( ctx );
      out.write("/assets/image/logo.jpg\"\r\n");
      out.write("         alt=\"Logo\"\r\n");
      out.write("         style=\"width:60px; height:60px; border-radius:6px; object-fit:cover;\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Title + Navigation -->\r\n");
      out.write("    <div>\r\n");
      out.write("        <h2 class=\"fw-bold mb-1\">CyberLearn</h2>\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"top-nav d-flex gap-4\">\r\n");
      out.write("\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/index.jsp\">Home</a>\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/courses\">Courses</a>\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/labs\">Labs</a>\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/forum\">Forum</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/dashboard.css\">\n");
      out.write("\n");

    User user = (User) session.getAttribute("user");
    if (user == null || !user.isAdmin()) {
        response.sendRedirect(request.getContextPath() + "/login");
        return;
    }

      out.write("\n");
      out.write("\n");
      out.write("<div class=\"main-area\" style=\"margin-left:260px; padding:28px;\">\n");
      out.write("  <div class=\"card-dark\" style=\"padding:24px; margin-bottom:18px;\">\n");
      out.write("    <h2 style=\"margin:0 0 8px 0;\">Admin: Add New Course</h2>\n");
      out.write("\n");
      out.write("    <!-- FIXED action: must match AdminServlet doPost -->\n");
      out.write("    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin\" method=\"post\" style=\"margin-top:12px;\">\n");
      out.write("      <input type=\"text\" name=\"title\" placeholder=\"Course Title\" class=\"form-control-dark\" required style=\"width:60%; margin-bottom:12px;\">\n");
      out.write("      <textarea name=\"description\" placeholder=\"Course Description\" class=\"form-control-dark\" style=\"width:60%; height:120px;\"></textarea>\n");
      out.write("      <div style=\"margin-top:12px;\">\n");
      out.write("        <button class=\"btn-teal\">Add Course</button>\n");
      out.write("      </div>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div class=\"card-dark\" style=\"padding:20px;\">\n");
      out.write("    <h3 style=\"margin-top:0;\">Existing Courses</h3>\n");
      out.write("    <table style=\"width:100%; border-collapse:collapse; margin-top:12px;\">\n");
      out.write("      <thead>\n");
      out.write("        <tr style=\"text-align:left; color:var(--muted);\">\n");
      out.write("          <th style=\"padding:10px 6px;\">Title</th>\n");
      out.write("          <th style=\"padding:10px 6px;\">Description</th>\n");
      out.write("          <th style=\"padding:10px 6px;\">Actions</th>\n");
      out.write("        </tr>\n");
      out.write("      </thead>\n");
      out.write("      <tbody>\n");
      out.write("\n");
      out.write("        <!-- Example row -->\n");
      out.write("        <tr style=\"border-top:1px solid rgba(255,255,255,0.02);\">\n");
      out.write("          <td style=\"padding:12px 6px;\">Network Penetration Testing</td>\n");
      out.write("          <td style=\"padding:12px 6px; color:var(--muted);\">Advanced pentesting course</td>\n");
      out.write("          <td style=\"padding:12px 6px;\">\n");
      out.write("            <a class=\"btn btn-teal\" href=\"#\">Edit</a>\n");
      out.write("            <a class=\"btn\" style=\"background:rgba(255,255,255,0.02); color:var(--muted); margin-left:8px;\" href=\"#\">Delete</a>\n");
      out.write("          </td>\n");
      out.write("        </tr>\n");
      out.write("\n");
      out.write("      </tbody>\n");
      out.write("    </table>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\r\n");
      out.write("<footer class=\"site-footer container\">\r\n");
      out.write("  &copy; ");
      out.print( java.time.Year.now() );
      out.write(" CyberLearn. All rights reserved.\r\n");
      out.write("</footer>\n");
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
