/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-11-20 11:38:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>CyberLearn - Your Cyber Security Learning Platform</title>\r\n");
      out.write("    <!-- Font Awesome Icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #0f0c29, #302b63, #24243e);\r\n");
      out.write("            color: #e0e0e0;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Animated Background Glow */\r\n");
      out.write("        body::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            width: 400px;\r\n");
      out.write("            height: 400px;\r\n");
      out.write("            background: radial-gradient(circle, rgba(100, 200, 255, 0.3), transparent);\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            top: -100px;\r\n");
      out.write("            left: -100px;\r\n");
      out.write("            animation: float 15s infinite ease-in-out;\r\n");
      out.write("            z-index: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            width: 300px;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            background: radial-gradient(circle, rgba(255, 100, 200, 0.2), transparent);\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            bottom: -50px;\r\n");
      out.write("            right: -50px;\r\n");
      out.write("            animation: float 20s infinite ease-in-out reverse;\r\n");
      out.write("            z-index: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes float {\r\n");
      out.write("            0%, 100% { transform: translate(0, 0); }\r\n");
      out.write("            50% { transform: translate(50px, 50px); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 60px 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header-section {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 80px;\r\n");
      out.write("            animation: slideDown 0.8s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes slideDown {\r\n");
      out.write("            from {\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("                transform: translateY(-30px);\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            font-size: 3.5rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            background: linear-gradient(135deg, #64c8ff, #ff64c8);\r\n");
      out.write("            -webkit-background-clip: text;\r\n");
      out.write("            -webkit-text-fill-color: transparent;\r\n");
      out.write("            background-clip: text;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            text-shadow: 0 0 30px rgba(100, 200, 255, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .subtitle {\r\n");
      out.write("            font-size: 1.3rem;\r\n");
      out.write("            color: #b0b0b0;\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("            font-weight: 300;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Feature Cards Grid */\r\n");
      out.write("        .features-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\r\n");
      out.write("            gap: 30px;\r\n");
      out.write("            margin-bottom: 60px;\r\n");
      out.write("            animation: slideUp 0.8s ease-out 0.2s both;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes slideUp {\r\n");
      out.write("            from {\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("                transform: translateY(30px);\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature-card {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.08);\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.15);\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            padding: 40px 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.4s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature-card::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: linear-gradient(135deg, rgba(100, 200, 255, 0.2), rgba(255, 100, 200, 0.2));\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            transition: opacity 0.4s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature-card:hover {\r\n");
      out.write("            transform: translateY(-15px);\r\n");
      out.write("            border-color: rgba(100, 200, 255, 0.5);\r\n");
      out.write("            box-shadow: 0 20px 60px rgba(100, 200, 255, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature-card:hover::before {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .icon {\r\n");
      out.write("            font-size: 3.5rem;\r\n");
      out.write("            color: #64c8ff;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            transition: all 0.4s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature-card:hover .icon {\r\n");
      out.write("            color: #ff64c8;\r\n");
      out.write("            transform: scale(1.2) rotate(10deg);\r\n");
      out.write("            text-shadow: 0 0 20px rgba(255, 100, 200, 0.8);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature-card h3 {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature-card p {\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            color: #c0c0c0;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Login Button */\r\n");
      out.write("        .btn {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            padding: 16px 50px;\r\n");
      out.write("            background: linear-gradient(135deg, #64c8ff, #00d4ff);\r\n");
      out.write("            color: #0f0c29;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.4s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            box-shadow: 0 10px 30px rgba(100, 200, 255, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: -100%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: linear-gradient(135deg, #ff64c8, #64c8ff);\r\n");
      out.write("            transition: left 0.4s ease;\r\n");
      out.write("            z-index: -1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:hover {\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 15px 40px rgba(100, 200, 255, 0.6);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:hover::before {\r\n");
      out.write("            left: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cta-section {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            animation: slideUp 0.8s ease-out 0.4s both;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cta-section p {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            color: #b0b0b0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            h2 {\r\n");
      out.write("                font-size: 2.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .subtitle {\r\n");
      out.write("                font-size: 1.1rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .features-grid {\r\n");
      out.write("                grid-template-columns: 1fr;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .feature-card {\r\n");
      out.write("                padding: 30px 20px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .icon {\r\n");
      out.write("                font-size: 2.5rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"header-section\">\r\n");
      out.write("            <h2>Welcome to CyberLearn</h2>\r\n");
      out.write("            <p class=\"subtitle\">Your Cyber Security Learning Platform</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"features-grid\">\r\n");
      out.write("            <div class=\"feature-card\">\r\n");
      out.write("                <div class=\"icon\"><i class=\"fas fa-shield-alt\"></i></div>\r\n");
      out.write("                <h3>Security Fundamentals</h3>\r\n");
      out.write("                <p>Learn the core principles of cybersecurity and best practices</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"feature-card\">\r\n");
      out.write("                <div class=\"icon\"><i class=\"fas fa-code\"></i></div>\r\n");
      out.write("                <h3>Ethical Hacking</h3>\r\n");
      out.write("                <p>Master penetration testing and secure coding techniques</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"feature-card\">\r\n");
      out.write("                <div class=\"icon\"><i class=\"fas fa-user-graduate\"></i></div>\r\n");
      out.write("                <h3>Expert Training</h3>\r\n");
      out.write("                <p>Learn from industry professionals and certified instructors</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"feature-card\">\r\n");
      out.write("                <div class=\"icon\"><i class=\"fas fa-network-wired\"></i></div>\r\n");
      out.write("                <h3>Network Security</h3>\r\n");
      out.write("                <p>Understand firewalls, VPNs, and network protection protocols</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"feature-card\">\r\n");
      out.write("                <div class=\"icon\"><i class=\"fas fa-lock\"></i></div>\r\n");
      out.write("                <h3>Cryptography</h3>\r\n");
      out.write("                <p>Explore encryption, decryption, and secure communications</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"feature-card\">\r\n");
      out.write("                <div class=\"icon\"><i class=\"fas fa-certificate\"></i></div>\r\n");
      out.write("                <h3>Certifications</h3>\r\n");
      out.write("                <p>Earn recognized credentials in cybersecurity domains</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"cta-section\">\r\n");
      out.write("            <p>Ready to enhance your cybersecurity skills?</p>\r\n");
      out.write("            <a class=\"btn\" href=\"login.jsp\">Login</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
