/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-11-20 13:17:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class certifications_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1763621232000L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1763638666000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String ctx = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- BOOTSTRAP CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- BOOTSTRAP ICONS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- CUSTOM CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( ctx );
      out.write("/assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- BOOTSTRAP JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<header class=\"site-header container mt-4 mb-3 d-flex align-items-center gap-3\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Logo -->\r\n");
      out.write("    <img src=\"");
      out.print( ctx );
      out.write("/assets/image/logo.jpg\"\r\n");
      out.write("         alt=\"Logo\"\r\n");
      out.write("         style=\"width:60px; height:60px; border-radius:6px; object-fit:cover;\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Title + Navigation -->\r\n");
      out.write("    <div>\r\n");
      out.write("        <h2 class=\"fw-bold mb-1\">CyberLearn</h2>\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"top-nav d-flex gap-4\">\r\n");
      out.write("\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/index.jsp\">Home</a>\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/courses\">Courses</a>\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/labs\">Labs</a>\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/forum\">Forum</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    * {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        background: linear-gradient(135deg, #0a0e27 0%, #1a1a3e 50%, #0f0f2e 100%);\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        overflow-x: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .glow-bg {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        width: 400px;\r\n");
      out.write("        height: 400px;\r\n");
      out.write("        background: radial-gradient(circle, rgba(99, 102, 241, 0.3) 0%, transparent 70%);\r\n");
      out.write("        border-radius: 50%;\r\n");
      out.write("        filter: blur(40px);\r\n");
      out.write("        animation: float1 20s ease-in-out infinite;\r\n");
      out.write("        z-index: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .glow-bg:nth-child(2) {\r\n");
      out.write("        animation: float2 25s ease-in-out infinite;\r\n");
      out.write("        right: 100px;\r\n");
      out.write("        top: 50%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes float1 {\r\n");
      out.write("        0%, 100% { transform: translate(0, 0); }\r\n");
      out.write("        50% { transform: translate(50px, 50px); }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes float2 {\r\n");
      out.write("        0%, 100% { transform: translate(0, 0); }\r\n");
      out.write("        50% { transform: translate(-50px, -50px); }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        z-index: 1;\r\n");
      out.write("        max-width: 1200px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        padding: 40px 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .header-section {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        margin-bottom: 50px;\r\n");
      out.write("        gap: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h2 {\r\n");
      out.write("        font-size: 2.5rem;\r\n");
      out.write("        background: linear-gradient(135deg, #6366f1 0%, #a78bfa 100%);\r\n");
      out.write("        -webkit-background-clip: text;\r\n");
      out.write("        -webkit-text-fill-color: transparent;\r\n");
      out.write("        background-clip: text;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .back-button {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 8px;\r\n");
      out.write("        padding: 12px 24px;\r\n");
      out.write("        background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("        border: 1px solid rgba(99, 102, 241, 0.5);\r\n");
      out.write("        border-radius: 50px;\r\n");
      out.write("        color: #a78bfa;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-size: 0.95rem;\r\n");
      out.write("        backdrop-filter: blur(10px);\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .back-button:hover {\r\n");
      out.write("        background: rgba(99, 102, 241, 0.2);\r\n");
      out.write("        border-color: #a78bfa;\r\n");
      out.write("        box-shadow: 0 0 20px rgba(167, 139, 250, 0.5);\r\n");
      out.write("        transform: translateX(-5px);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .certifications-grid {\r\n");
      out.write("        display: grid;\r\n");
      out.write("        grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\r\n");
      out.write("        gap: 30px;\r\n");
      out.write("        margin-top: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .cert-card {\r\n");
      out.write("        background: rgba(255, 255, 255, 0.05);\r\n");
      out.write("        border: 1px solid rgba(99, 102, 241, 0.3);\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        padding: 30px;\r\n");
      out.write("        backdrop-filter: blur(10px);\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("        animation: slideUp 0.6s ease forwards;\r\n");
      out.write("        opacity: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .cert-card:nth-child(1) { animation-delay: 0.1s; }\r\n");
      out.write("    .cert-card:nth-child(2) { animation-delay: 0.2s; }\r\n");
      out.write("    .cert-card:nth-child(3) { animation-delay: 0.3s; }\r\n");
      out.write("    .cert-card:nth-child(4) { animation-delay: 0.4s; }\r\n");
      out.write("    .cert-card:nth-child(5) { animation-delay: 0.5s; }\r\n");
      out.write("    .cert-card:nth-child(6) { animation-delay: 0.6s; }\r\n");
      out.write("\r\n");
      out.write("    @keyframes slideUp {\r\n");
      out.write("        from {\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            transform: translateY(30px);\r\n");
      out.write("        }\r\n");
      out.write("        to {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("            transform: translateY(0);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .cert-card:hover {\r\n");
      out.write("        background: rgba(99, 102, 241, 0.15);\r\n");
      out.write("        border-color: #a78bfa;\r\n");
      out.write("        transform: translateY(-10px);\r\n");
      out.write("        box-shadow: 0 20px 40px rgba(99, 102, 241, 0.3);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .cert-icon {\r\n");
      out.write("        font-size: 2.5rem;\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        width: 60px;\r\n");
      out.write("        height: 60px;\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        background: linear-gradient(135deg, #6366f1, #a78bfa);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .cert-card:nth-child(1) .cert-icon { background: linear-gradient(135deg, #6366f1, #a78bfa); }\r\n");
      out.write("    .cert-card:nth-child(2) .cert-icon { background: linear-gradient(135deg, #ec4899, #f43f5e); }\r\n");
      out.write("    .cert-card:nth-child(3) .cert-icon { background: linear-gradient(135deg, #3b82f6, #06b6d4); }\r\n");
      out.write("    .cert-card:nth-child(4) .cert-icon { background: linear-gradient(135deg, #10b981, #14b8a6); }\r\n");
      out.write("    .cert-card:nth-child(5) .cert-icon { background: linear-gradient(135deg, #f59e0b, #d97706); }\r\n");
      out.write("    .cert-card:nth-child(6) .cert-icon { background: linear-gradient(135deg, #8b5cf6, #d946ef); }\r\n");
      out.write("\r\n");
      out.write("    .cert-icon i {\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .cert-title {\r\n");
      out.write("        font-size: 1.3rem;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .cert-course {\r\n");
      out.write("        font-size: 0.9rem;\r\n");
      out.write("        color: #a78bfa;\r\n");
      out.write("        margin-bottom: 8px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .cert-meta {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        margin-top: 15px;\r\n");
      out.write("        padding-top: 15px;\r\n");
      out.write("        border-top: 1px solid rgba(99, 102, 241, 0.2);\r\n");
      out.write("        font-size: 0.85rem;\r\n");
      out.write("        color: #94a3b8;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .cert-id {\r\n");
      out.write("        font-family: monospace;\r\n");
      out.write("        color: #6366f1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .cert-year {\r\n");
      out.write("        background: rgba(99, 102, 241, 0.2);\r\n");
      out.write("        padding: 4px 12px;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        color: #a78bfa;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"glow-bg\"></div>\r\n");
      out.write("<div class=\"glow-bg\"></div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"header-section\">\r\n");
      out.write("        <h2>My Certifications</h2>\r\n");
      out.write("        <!-- <CHANGE> Updated back button path to correct dashboard location -->\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/dashboard.jsp\" class=\"back-button\">\r\n");
      out.write("            <i class=\"fas fa-arrow-left\"></i> Back to Dashboard\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"certifications-grid\">\r\n");
      out.write("        <div class=\"cert-card\">\r\n");
      out.write("            <div class=\"cert-icon\"><i class=\"fas fa-shield-alt\"></i></div>\r\n");
      out.write("            <div class=\"cert-title\">Network Security Certified</div>\r\n");
      out.write("            <div class=\"cert-course\">Course: Network Fundamentals</div>\r\n");
      out.write("            <div class=\"cert-meta\">\r\n");
      out.write("                <span class=\"cert-id\">NSC-2024-001</span>\r\n");
      out.write("                <span class=\"cert-year\">2024</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"cert-card\">\r\n");
      out.write("            <div class=\"cert-icon\"><i class=\"fas fa-code\"></i></div>\r\n");
      out.write("            <div class=\"cert-title\">Ethical Hacking Pro</div>\r\n");
      out.write("            <div class=\"cert-course\">Course: Penetration Testing</div>\r\n");
      out.write("            <div class=\"cert-meta\">\r\n");
      out.write("                <span class=\"cert-id\">EHP-2024-002</span>\r\n");
      out.write("                <span class=\"cert-year\">2024</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"cert-card\">\r\n");
      out.write("            <div class=\"cert-icon\"><i class=\"fas fa-lock\"></i></div>\r\n");
      out.write("            <div class=\"cert-title\">Cryptography Expert</div>\r\n");
      out.write("            <div class=\"cert-course\">Course: Encryption & Algorithms</div>\r\n");
      out.write("            <div class=\"cert-meta\">\r\n");
      out.write("                <span class=\"cert-id\">CE-2024-003</span>\r\n");
      out.write("                <span class=\"cert-year\">2024</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"cert-card\">\r\n");
      out.write("            <div class=\"cert-icon\"><i class=\"fas fa-user-shield\"></i></div>\r\n");
      out.write("            <div class=\"cert-title\">Identity & Access Master</div>\r\n");
      out.write("            <div class=\"cert-course\">Course: IAM Systems</div>\r\n");
      out.write("            <div class=\"cert-meta\">\r\n");
      out.write("                <span class=\"cert-id\">IAM-2024-004</span>\r\n");
      out.write("                <span class=\"cert-year\">2024</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"cert-card\">\r\n");
      out.write("            <div class=\"cert-icon\"><i class=\"fas fa-virus\"></i></div>\r\n");
      out.write("            <div class=\"cert-title\">Malware Analysis Specialist</div>\r\n");
      out.write("            <div class=\"cert-course\">Course: Threat Detection</div>\r\n");
      out.write("            <div class=\"cert-meta\">\r\n");
      out.write("                <span class=\"cert-id\">MAS-2024-005</span>\r\n");
      out.write("                <span class=\"cert-year\">2024</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"cert-card\">\r\n");
      out.write("            <div class=\"cert-icon\"><i class=\"fas fa-server\"></i></div>\r\n");
      out.write("            <div class=\"cert-title\">Cloud Security Certified</div>\r\n");
      out.write("            <div class=\"cert-course\">Course: Cloud Infrastructure</div>\r\n");
      out.write("            <div class=\"cert-meta\">\r\n");
      out.write("                <span class=\"cert-id\">CSC-2024-006</span>\r\n");
      out.write("                <span class=\"cert-year\">2024</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer class=\"site-footer container\">\r\n");
      out.write("  &copy; ");
      out.print( java.time.Year.now() );
      out.write(" CyberLearn. All rights reserved.\r\n");
      out.write("</footer>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
