/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-11-20 11:43:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.cyberlearn.model.User;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1763621232000L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1763638666000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.cyberlearn.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

    String ctx = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- BOOTSTRAP CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- BOOTSTRAP ICONS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- CUSTOM CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( ctx );
      out.write("/assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- BOOTSTRAP JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<header class=\"site-header container mt-4 mb-3 d-flex align-items-center gap-3\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Logo -->\r\n");
      out.write("    <img src=\"");
      out.print( ctx );
      out.write("/assets/image/logo.jpg\"\r\n");
      out.write("         alt=\"Logo\"\r\n");
      out.write("         style=\"width:60px; height:60px; border-radius:6px; object-fit:cover;\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Title + Navigation -->\r\n");
      out.write("    <div>\r\n");
      out.write("        <h2 class=\"fw-bold mb-1\">CyberLearn</h2>\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"top-nav d-flex gap-4\">\r\n");
      out.write("\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/index.jsp\">Home</a>\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/courses\">Courses</a>\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/labs\">Labs</a>\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/forum\">Forum</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/dashboard.css\">\r\n");
      out.write("\r\n");

    User user = (User) session.getAttribute("user");
    String name = (user!=null && user.getName()!=null) ? user.getName() : "Learner";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"app-layout\">\r\n");
      out.write("  <!-- SIDEBAR -->\r\n");
      out.write("  <aside class=\"app-sidebar\">\r\n");
      out.write("\r\n");
      out.write("      <nav class=\"app-nav\">\r\n");
      out.write("        <a class=\"active\" href=\"");
      out.print( request.getContextPath() );
      out.write("/user/dashboard.jsp\"><i class=\"bi bi-grid-1x2\"></i> Dashboard</a>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/courses/courses.jsp\"><i class=\"bi bi-journal-bookmark\"></i> My Courses</a>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/labs/labs.jsp\"><i class=\"bi bi-terminal\"></i> Labs</a>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/certifications.jsp\"><i class=\"bi bi-award\"></i> Certifications</a>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/forum/forum.jsp\"><i class=\"bi bi-chat-dots\"></i> Community Forum</a>\r\n");
      out.write("      </nav>\r\n");
      out.write("  </aside>\r\n");
      out.write("\r\n");
      out.write("  <!-- MAIN AREA -->\r\n");
      out.write("  <main class=\"main-area\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"topbar\">\r\n");
      out.write("      <div>\r\n");
      out.write("        <h1 style=\"margin:0; font-size:26px;\">Dashboard</h1>\r\n");
      out.write("        <div style=\"color:var(--muted); margin-top:6px;\">Welcome back, <strong>");
      out.print( name );
      out.write("</strong>! Ready to learn?</div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div style=\"display:flex; gap:12px; align-items:center;\">\r\n");
      out.write("        <div style=\"background:rgba(255,255,255,0.02); padding:8px 12px; border-radius:10px;\">\r\n");
      out.write("          <i class=\"bi bi-bell\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"background:rgba(255,255,255,0.02); padding:8px 12px; border-radius:10px;\">\r\n");
      out.write("          <i class=\"bi bi-search\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"welcome card-dark\">\r\n");
      out.write("      <div>\r\n");
      out.write("        <h2 style=\"margin:0 0 6px 0;\">Hello, ");
      out.print( name );
      out.write("</h2>\r\n");
      out.write("        <div style=\"color:var(--muted)\">Track your progress, practice labs and earn certifications.</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <button class=\"btn-teal\">Continue Learning</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"grid-2\">\r\n");
      out.write("      <div>\r\n");
      out.write("        <div class=\"card-dark\" style=\"margin-bottom:18px;\">\r\n");
      out.write("          <h4 style=\"margin:0 0 12px 0;\">Courses in Progress</h4>\r\n");
      out.write("\r\n");
      out.write("          <div style=\"margin-bottom:12px;\">\r\n");
      out.write("            <div style=\"display:flex; justify-content:space-between;\">\r\n");
      out.write("              <div><strong>Network Penetration Testing</strong></div>\r\n");
      out.write("              <div style=\"color:var(--muted)\">75%</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"progress-wrap\">\r\n");
      out.write("              <div class=\"progress-bar-custom\">\r\n");
      out.write("                <div class=\"progress-bar-fill\" style=\"width:75%\"></div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div>\r\n");
      out.write("            <div style=\"display:flex; justify-content:space-between;\">\r\n");
      out.write("              <div><strong>Mobile Application Security</strong></div>\r\n");
      out.write("              <div style=\"color:var(--muted)\">40%</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"progress-wrap\">\r\n");
      out.write("              <div class=\"progress-bar-custom\">\r\n");
      out.write("                <div class=\"progress-bar-fill\" style=\"width:40%\"></div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-dark\">\r\n");
      out.write("          <h4 style=\"margin:0 0 12px 0;\">Recent Lab Activity</h4>\r\n");
      out.write("          <div style=\"display:flex; flex-direction:column; gap:12px;\">\r\n");
      out.write("            <div style=\"display:flex; justify-content:space-between; align-items:center;\">\r\n");
      out.write("              <div>\r\n");
      out.write("                <div style=\"font-weight:600\">SQL Injection Playground</div>\r\n");
      out.write("                <div style=\"color:var(--muted); font-size:13px;\">Completed: 2 days ago</div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div style=\"background:var(--glass); padding:6px 10px; border-radius:20px; color:var(--success); font-weight:600;\">Completed</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div style=\"display:flex; justify-content:space-between; align-items:center;\">\r\n");
      out.write("              <div>\r\n");
      out.write("                <div style=\"font-weight:600\">Cross-Site Scripting (XSS) Challenge</div>\r\n");
      out.write("                <div style=\"color:var(--muted); font-size:13px;\">Started: 8 hours ago</div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div style=\"background:rgba(255,255,255,0.02); padding:6px 10px; border-radius:20px; color:var(--warning); font-weight:600;\">In Progress</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <aside>\r\n");
      out.write("        <div class=\"card-dark\" style=\"margin-bottom:18px; padding:18px;\">\r\n");
      out.write("          <h5 style=\"margin-top:0;\">Certifications</h5>\r\n");
      out.write("          <div style=\"margin-top:12px;\">\r\n");
      out.write("            <div style=\"display:flex; justify-content:space-between; align-items:center; margin-bottom:10px;\">\r\n");
      out.write("              <div>\r\n");
      out.write("                <div style=\"font-weight:600\">Certified Ethical Hacker (CEH)</div>\r\n");
      out.write("                <div style=\"color:var(--muted); font-size:13px;\">Status: Not Started</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"display:flex; justify-content:space-between; align-items:center;\">\r\n");
      out.write("              <div>\r\n");
      out.write("                <div style=\"font-weight:600\">OSCP</div>\r\n");
      out.write("                <div style=\"color:var(--muted); font-size:13px;\">Status: Locked</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div style=\"margin-top:12px;\">\r\n");
      out.write("              <button class=\"btn-teal w-100\">View All</button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-dark forum-card\">\r\n");
      out.write("          <h5 style=\"margin-top:0;\">Latest Forum Posts</h5>\r\n");
      out.write("          <div style=\"margin-top:12px;\">\r\n");
      out.write("            <div class=\"post\">\r\n");
      out.write("              <div style=\"width:42px; height:42px; background:rgba(255,255,255,0.03); border-radius:8px;\"></div>\r\n");
      out.write("              <div>\r\n");
      out.write("                <div style=\"font-weight:600\">How to set up a secure home lab?</div>\r\n");
      out.write("                <div style=\"color:var(--muted); font-size:13px;\">by Jane Doe â¢ 5 replies</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"post\">\r\n");
      out.write("              <div style=\"width:42px; height:42px; background:rgba(255,255,255,0.03); border-radius:8px;\"></div>\r\n");
      out.write("              <div>\r\n");
      out.write("                <div style=\"font-weight:600\">Best resources for learning Python for hacking</div>\r\n");
      out.write("                <div style=\"color:var(--muted); font-size:13px;\">by John Smith â¢ 12 replies</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </aside>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </main>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer class=\"site-footer container\">\r\n");
      out.write("  &copy; ");
      out.print( java.time.Year.now() );
      out.write(" CyberLearn. All rights reserved.\r\n");
      out.write("</footer>\n");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
