/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-11-20 12:02:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.courses;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class courses_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1763621232000L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1763638666000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String ctx = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- BOOTSTRAP CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- BOOTSTRAP ICONS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- CUSTOM CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( ctx );
      out.write("/assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- BOOTSTRAP JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<header class=\"site-header container mt-4 mb-3 d-flex align-items-center gap-3\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Logo -->\r\n");
      out.write("    <img src=\"");
      out.print( ctx );
      out.write("/assets/image/logo.jpg\"\r\n");
      out.write("         alt=\"Logo\"\r\n");
      out.write("         style=\"width:60px; height:60px; border-radius:6px; object-fit:cover;\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Title + Navigation -->\r\n");
      out.write("    <div>\r\n");
      out.write("        <h2 class=\"fw-bold mb-1\">CyberLearn</h2>\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"top-nav d-flex gap-4\">\r\n");
      out.write("\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/index.jsp\">Home</a>\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/courses\">Courses</a>\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/labs\">Labs</a>\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/forum\">Forum</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Available Courses - CyberLearn</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #0a0e27 0%, #16213e 50%, #0f3460 100%);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Animated Background Glow */\r\n");
      out.write("        body::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: -50%;\r\n");
      out.write("            left: -50%;\r\n");
      out.write("            width: 200%;\r\n");
      out.write("            height: 200%;\r\n");
      out.write("            background: radial-gradient(circle, rgba(0, 150, 255, 0.1) 0%, rgba(0, 100, 200, 0.05) 30%, transparent 70%);\r\n");
      out.write("            animation: floatGlow 15s ease-in-out infinite;\r\n");
      out.write("            pointer-events: none;\r\n");
      out.write("            z-index: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: -50%;\r\n");
      out.write("            right: -50%;\r\n");
      out.write("            width: 200%;\r\n");
      out.write("            height: 200%;\r\n");
      out.write("            background: radial-gradient(circle, rgba(100, 50, 255, 0.1) 0%, rgba(50, 100, 200, 0.05) 30%, transparent 70%);\r\n");
      out.write("            animation: floatGlow 20s ease-in-out infinite reverse;\r\n");
      out.write("            pointer-events: none;\r\n");
      out.write("            z-index: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes floatGlow {\r\n");
      out.write("            0%, 100% {\r\n");
      out.write("                transform: translate(0, 0);\r\n");
      out.write("            }\r\n");
      out.write("            50% {\r\n");
      out.write("                transform: translate(50px, 50px);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 40px 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-btn {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("            padding: 12px 24px;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("            color: #00d4ff;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-btn:hover {\r\n");
      out.write("            background: rgba(0, 212, 255, 0.2);\r\n");
      out.write("            border-color: rgba(0, 212, 255, 0.5);\r\n");
      out.write("            transform: translateX(-5px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            background: linear-gradient(135deg, #00d4ff 0%, #0099ff 100%);\r\n");
      out.write("            -webkit-background-clip: text;\r\n");
      out.write("            -webkit-text-fill-color: transparent;\r\n");
      out.write("            background-clip: text;\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .courses-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));\r\n");
      out.write("            gap: 30px;\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .course-card {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.08);\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.15);\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            animation: float 3s ease-in-out infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .course-card:nth-child(1) { animation-delay: 0s; }\r\n");
      out.write("        .course-card:nth-child(2) { animation-delay: 0.2s; }\r\n");
      out.write("        .course-card:nth-child(3) { animation-delay: 0.4s; }\r\n");
      out.write("        .course-card:nth-child(4) { animation-delay: 0.6s; }\r\n");
      out.write("        .course-card:nth-child(5) { animation-delay: 0.8s; }\r\n");
      out.write("        .course-card:nth-child(6) { animation-delay: 1s; }\r\n");
      out.write("\r\n");
      out.write("        @keyframes float {\r\n");
      out.write("            0%, 100% {\r\n");
      out.write("                transform: translateY(0px);\r\n");
      out.write("            }\r\n");
      out.write("            50% {\r\n");
      out.write("                transform: translateY(-10px);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .course-card:hover {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.12);\r\n");
      out.write("            border-color: rgba(0, 212, 255, 0.5);\r\n");
      out.write("            transform: translateY(-15px);\r\n");
      out.write("            box-shadow: 0 20px 40px rgba(0, 212, 255, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .icon-container {\r\n");
      out.write("            width: 60px;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("            background: linear-gradient(135deg, #00d4ff, #0099ff);\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .course-card:nth-child(2) .icon-container {\r\n");
      out.write("            background: linear-gradient(135deg, #ff006e, #8338ec);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .course-card:nth-child(3) .icon-container {\r\n");
      out.write("            background: linear-gradient(135deg, #06ffa5, #00d4ff);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .course-card:nth-child(4) .icon-container {\r\n");
      out.write("            background: linear-gradient(135deg, #ffbe0b, #fb5607);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .course-card:nth-child(5) .icon-container {\r\n");
      out.write("            background: linear-gradient(135deg, #7209b7, #3a0ca3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .course-card:nth-child(6) .icon-container {\r\n");
      out.write("            background: linear-gradient(135deg, #f72585, #b5179e);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .course-title {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            color: #00d4ff;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            margin-bottom: 12px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .course-description {\r\n");
      out.write("            color: rgba(255, 255, 255, 0.7);\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            margin-bottom: 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .course-meta {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 16px;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.6);\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .meta-item {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 6px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .meta-item i {\r\n");
      out.write("            color: #00d4ff;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/dashboard.jsp\" class=\"back-btn\">\r\n");
      out.write("            <i class=\"fas fa-arrow-left\"></i> Back to Dashboard\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <h2>Available Courses</h2>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"courses-grid\">\r\n");
      out.write("            <!-- Course Card 1 -->\r\n");
      out.write("            <div class=\"course-card\">\r\n");
      out.write("                <div class=\"icon-container\">\r\n");
      out.write("                    <i class=\"fas fa-shield-alt\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"course-title\">Network Security Fundamentals</h3>\r\n");
      out.write("                <p class=\"course-description\">Learn the basics of network security, firewalls, and intrusion detection systems to protect your infrastructure.</p>\r\n");
      out.write("                <div class=\"course-meta\">\r\n");
      out.write("                    <div class=\"meta-item\">\r\n");
      out.write("                        <i class=\"fas fa-clock\"></i>\r\n");
      out.write("                        <span>40 hours</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"meta-item\">\r\n");
      out.write("                        <i class=\"fas fa-star\"></i>\r\n");
      out.write("                        <span>Beginner</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Course Card 2 -->\r\n");
      out.write("            <div class=\"course-card\">\r\n");
      out.write("                <div class=\"icon-container\">\r\n");
      out.write("                    <i class=\"fas fa-code\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"course-title\">Ethical Hacking Essentials</h3>\r\n");
      out.write("                <p class=\"course-description\">Master penetration testing techniques and learn how to identify vulnerabilities in systems ethically.</p>\r\n");
      out.write("                <div class=\"course-meta\">\r\n");
      out.write("                    <div class=\"meta-item\">\r\n");
      out.write("                        <i class=\"fas fa-clock\"></i>\r\n");
      out.write("                        <span>50 hours</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"meta-item\">\r\n");
      out.write("                        <i class=\"fas fa-star\"></i>\r\n");
      out.write("                        <span>Intermediate</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Course Card 3 -->\r\n");
      out.write("            <div class=\"course-card\">\r\n");
      out.write("                <div class=\"icon-container\">\r\n");
      out.write("                    <i class=\"fas fa-lock\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"course-title\">Cryptography & Encryption</h3>\r\n");
      out.write("                <p class=\"course-description\">Understand encryption algorithms, digital certificates, and secure communication protocols in depth.</p>\r\n");
      out.write("                <div class=\"course-meta\">\r\n");
      out.write("                    <div class=\"meta-item\">\r\n");
      out.write("                        <i class=\"fas fa-clock\"></i>\r\n");
      out.write("                        <span>35 hours</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"meta-item\">\r\n");
      out.write("                        <i class=\"fas fa-star\"></i>\r\n");
      out.write("                        <span>Advanced</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Course Card 4 -->\r\n");
      out.write("            <div class=\"course-card\">\r\n");
      out.write("                <div class=\"icon-container\">\r\n");
      out.write("                    <i class=\"fas fa-exclamation-triangle\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"course-title\">Malware Analysis</h3>\r\n");
      out.write("                <p class=\"course-description\">Learn to identify, analyze, and remove malware threats while understanding malicious code behavior.</p>\r\n");
      out.write("                <div class=\"course-meta\">\r\n");
      out.write("                    <div class=\"meta-item\">\r\n");
      out.write("                        <i class=\"fas fa-clock\"></i>\r\n");
      out.write("                        <span>45 hours</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"meta-item\">\r\n");
      out.write("                        <i class=\"fas fa-star\"></i>\r\n");
      out.write("                        <span>Advanced</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Course Card 5 -->\r\n");
      out.write("            <div class=\"course-card\">\r\n");
      out.write("                <div class=\"icon-container\">\r\n");
      out.write("                    <i class=\"fas fa-user-secret\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"course-title\">Social Engineering & OSINT</h3>\r\n");
      out.write("                <p class=\"course-description\">Understand social engineering tactics and open-source intelligence gathering techniques for security awareness.</p>\r\n");
      out.write("                <div class=\"course-meta\">\r\n");
      out.write("                    <div class=\"meta-item\">\r\n");
      out.write("                        <i class=\"fas fa-clock\"></i>\r\n");
      out.write("                        <span>25 hours</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"meta-item\">\r\n");
      out.write("                        <i class=\"fas fa-star\"></i>\r\n");
      out.write("                        <span>Intermediate</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Course Card 6 -->\r\n");
      out.write("            <div class=\"course-card\">\r\n");
      out.write("                <div class=\"icon-container\">\r\n");
      out.write("                    <i class=\"fas fa-server\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"course-title\">Cloud Security & Compliance</h3>\r\n");
      out.write("                <p class=\"course-description\">Secure cloud environments, manage identity and access, and implement compliance frameworks effectively.</p>\r\n");
      out.write("                <div class=\"course-meta\">\r\n");
      out.write("                    <div class=\"meta-item\">\r\n");
      out.write("                        <i class=\"fas fa-clock\"></i>\r\n");
      out.write("                        <span>38 hours</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"meta-item\">\r\n");
      out.write("                        <i class=\"fas fa-star\"></i>\r\n");
      out.write("                        <span>Intermediate</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<footer class=\"site-footer container\">\r\n");
      out.write("  &copy; ");
      out.print( java.time.Year.now() );
      out.write(" CyberLearn. All rights reserved.\r\n");
      out.write("</footer>\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
